name: unimove
description: Applicazione di carpooling per l'Università degli Studi del Molise.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Autenticazione & sicurezza
  flutter_secure_storage: ^9.2.2
  dart_jsonwebtoken: ^2.8.1

  # Navigazione
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true